### ISSUE TITLE
Followed the installation steups but not working Please help

### ISSUE THREAD

**Issue by leelavinodh** [frumbert/wp2moodle--wordpress-#12] opened 2015-05-27 01:32 UTC
Hi,

I followed your installation step, but after using the moodle button on the editor and published the page unable to show the page content. That is blank.

My Wordpress version is 4.2.2
Moodel Version is 2.9

Kindly help me to achive the SSO from wordpress to moodle.

Thank you

**Comment by Gianca76** [comment] 2015-05-30 14:48
Take a look at the name of the "wp2moodle" plugin folder inside "wordpress plugin folder" (wp-content/plugins). 
Probably you'll find something like wp2moodle--wordpress--master, I don't remember exactly, anyway rename it in "wp2moodle".

**Comment by shashidharamk** [comment] 2015-05-31 10:23
Dear Gianca,

Everything is correct still clicking on moodle course button shows a blank page

**Comment by shashidharamk** [comment] 2015-05-31 10:23
Please help
Thanks
shashidhara

**Comment by actXc** [comment] 2015-05-31 10:28
I added a pull request 
here is my code change that helped me:
https://github.com/actXc/wp2moodle-moodle/commit/43dfb730da6932b0bb5070342f93cc243f2b547a

working on http://my.extremoodle.de
I can also offer professional support on a hourly base.

**Comment by Gianca76** [comment] 2015-05-31 12:52
shashidharamk post your site or send me by email all the details and credentials to access
my email giancarlotrezzi@gmail.com

**Comment by shashidharamk** [comment] 2015-05-31 13:51
thank you. I have created a user account for you. The link on the home page
"Go to elearning Page"should take you moodle page but it does not work.
Please help.
shashi

**Comment by shashidharamk** [comment] 2015-05-31 14:17
New user registration on your site North West Preoperative Network:

Username: Gianca76

Email: giancarlotrezzi@gmail.com

**Comment by Gianca76** [comment] 2015-05-31 14:19
shashi wordpress seems to be OK, I think the problem is inside moodle.  Go here: http://elearning.nwpreop.co.uk/admin/settings.php?section=manageauths and check if Wordpress 2 Moodle (SSO) is in the list and is enabled
If you have skype send me your details, maybe we can chat there. (faster)

**Comment by shashidharamk** [comment] 2015-05-31 14:23
website is nwpreop.co.uk

**Comment by shashidharamk** [comment] 2015-05-31 14:56
I have checked and it is enabled 
Encryption key is same
Link Timeout is set to 15
Logoff url: www.nwpreop.co.uk
Autoopen course=No
Update user fields with wordpress:yes
skype name: shashidharamk

**Comment by shashidharamk** [comment] 2015-06-03 16:41
Hi Giancarlo,

I have discovered this is problem preventing the moodle opening with wordpress credentials to open. I need to sortout the php first
Thanks
shashi

Fatal error: Call to undefined method core\event\user_updated::create_from_userid() in /homepages/37/d575888969/htdocs/clickandbuilds/Moodle/NWPREOPElearningPortal/auth/wp2moodle/login.php on line 147

**Comment by frumbert** [comment] 2015-06-04 00:34
@shashidharamk : what is the specific version of Moodle that you are using? The event mentioned here (static core\event\user_updated::create_from_userid ( $userid )) was implemented in Moodle 2.6.4, 2.7.1. If your Moodle is older than 2.6.4 you'll have to use the 2.6 branch of this plugin (https://github.com/frumbert/wp2moodle-moodle/tree/moodle_26).

**Comment by frumbert** [comment] 2015-07-11 00:40
If there's nothing further to add, I'll close this ticket.

**Comment by shashidharamk** [comment] 2015-07-11 06:07
Yes please. There were errors in moodle side php which I couldn't rectify
and I am not using it any more.
Thanks
Shashi

**Comment by shashidharamk** [comment] 2015-07-11 06:43
yes please. There were errors on moodle part of php which i could not
rectify and i have decided not to use it. My moodle version was 2.9
Thanks
shashi

**Closed** 2015-07-12 11:41 UTC
